#指定具体的服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自己的端口
server:
  port: 8770

#自己的服务名
spring:
  application:
    name: could-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: could-ribben
    api-b:
      path: /api-b/**
      serviceId: could-feign

