server:
  port: 8765

spring:
  application:
    name: could-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
    prefer-ip-address: true

#开启断路器
feign:
  hystrix:
    enabled: true